[package]
name = "rcue"
version = "0.1.0"
authors = ["mygnu <tech@gill.net.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.6"
byteorder = "1.3"
